
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Linter
        run: npm run eslint
      # - name: Build
        # run: npm run build
      - name: Tests
        run: npm run test

      # - name: Deploy to heroku
      #   uses: akhileshns/heroku-deploy@v3.12.12
      #   with:
      #     heroku_api_key: ${{ secrets.HEROKU_KEY }}
      - name: Message test
        run: |
          echo "Var test" ${{ secrets.HEROKU_KEY }}


      # - name: Tests e2e
      #   uses: cypress-io/github-action@v6
      #   with:
      #     command: npm run test:e2e
      #     start: npm run dev
      #     wait-on: 'http://localhost:5000'
